user nginx;
worker_processes auto;
pid /run/nginx.pid;

events {
    # Connection handling
    worker_connections 1024;
}

http {
    # MIME types configuration
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Performance optimizations
    sendfile on;
    keepalive_timeout 65;

    # Virtual Server Block
    server {
        # Port configuration (IPv4 and IPv6)
        listen 80;
        listen [::]:80;

        # Domain name or server identification
        server_name localhost;

        # Root directory and default index files
        root /var/www/html;
        index index.html;

		# Path for page 404
		error_page 404 /404.html;
        location = /404.html {
            internal;
        }

        # Default request routing
        location / {
            try_files $uri $uri/ =404;
        }

        # Optional: PHP-FPM configuration for dynamic content (e.g., WordPress)
        # location ~ \.php$ {
        #     include fastcgi_params;
        #     fastcgi_intercept_errors on;
        #     fastcgi_pass wordpress:9000;
        #     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        # }
    }
}