# user nginx; nginx process running as restricted user (nginx)

# Virtual Server Block
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    # Domain name or server identification
    server_name localhost;

    # Paths to the TLS certificates
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Protocols restriction (Only those are allowed)
    ssl_protocols TLSv1.2 TLSv1.3;

    # Secure cipher suites definition
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers on;

    # Root directory and default index files
    root /var/www/html;
    index index.html;

    # Path for page 404
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    # Default request routing
    location / {
        try_files $uri $uri/ =404;
    }

    # Optional: PHP-FPM configuration for dynamic content (e.g., WordPress)
    # location ~ \.php$ {
    #     include fastcgi_params;
    #     fastcgi_intercept_errors on;
    #     fastcgi_pass wordpress:9000;
    #     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    # }
}
